/**
 * formConfigs.js — Official configuration for the 7 Canteen Smart Card Application Forms
 * Extracted directly from the official 14-page CSD Form Document.
 */

export const FORM_CATEGORIES = [
  {
    id: "cadetRecruit",
    prefix: "OS",
    title: "FOR SERVING CADETS/RECRUITS IN ALL THREE SERVICES",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR SERVING CADETS/RECRUITS IN ALL THREE SERVICES)",
    headerNote: "Note: Applicable for person holding Canteen Smart Cards of previous service (Like ACC/SCO).",
    description: "For serving cadets/recruits in all three services.",
    guidance: [
      "For serving cadets and recruits undergoing training in the Army, Navy, or Airforce.",
      "Card is valid for the duration of training across all canteens.",
      "Keep details of Date of Joining and Likely Date of Commissioning/Attestation handy.",
      "No PPO or dependent card information is required for this category.",
      "After printing, affix attested single passport photo and sign inside the designated box.",
    ],
  },
  {
    id: "agniveer",
    prefix: "SR",
    title: "AGNIVEER",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM - AGNIVEER",
    officialSubtitle: "",
    headerNote: "",
    description: "For serving Agniveers applying for the applicable Canteen Smart Card.",
    guidance: [
      "For serving Agniveers in the Army, Navy, or Airforce.",
      "Rank is permanently designated as AGNIVEER.",
      "Valid for up to four (4) years from the Date of Enrolment.",
      "You can apply for Liquor and/or Grocery cards.",
      "Keep Date of Enrolment and Date of Release (4 years from DOE) ready.",
      "Photo affixed on printed form must be in Civil Dress.",
    ],
  },
  {
    id: "retiringArmedForcesChangeCategory",
    prefix: "OE",
    title: "FOR RETIRING ARMED FORCES PERSON CHANGE OF CATEGORY - SERVING TO ESM",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(For Retiring Armed Forces Person Change of Category - Serving to ESM)",
    headerNote: "(To be filled 90 days before Retirement)",
    description: "For retiring Armed Forces personnel changing category from Serving to ESM.",
    guidance: [
      "To be filled 90 days prior to retirement date.",
      "Applicant categories include Superannuating, PMR/Discharge, or SSC.",
      "Provide presently held Liquor/Grocery Card Number.",
      "Up to two dependent cards can be requested for eligible family members.",
      "Requires both single passport photo and civil dress photo with spouse on the printed form.",
    ],
  },
  {
    id: "civilDefenceRetired",
    prefix: "OC",
    title: "FOR CIVIL DEFENCE EMPLOYEES (RETIRED, RETIRING & FAMILY PENSIONERS)",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR CIVIL DEFENCE EMPLOYEES (RETIRED, RETIRING & FAMILY PENSIONERS))",
    headerNote: "",
    description: "For eligible Civil Defence employees who are retired, retiring, widowed or NOK.",
    guidance: [
      "For retired or retiring defence civilian employees and family pensioners (Widow/NOK).",
      "Applicable for Army, Navy, Airforce, or MoD departments (e.g. AFHQ, DRDO, DGQA, BRO, etc.).",
      "PPO Number and Date are mandatory for retired personnel, widows, and NOK.",
      "Enter Pay Account Number as per salary slip.",
      "Requires countersignature from competent authority and authentication by URC.",
    ],
  },
  {
    id: "civilDefenceServing",
    prefix: "CC",
    title: "FOR SERVING CIVIL DEFENCE EMPLOYEES PAID OUT OF DEFENCE ESTIMATES/ ON DEPUTATION/OUT ON DEPUTATION FROM DEFENCE C",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR SERVING CIVIL DEFENCE EMPLOYEES PAID OUT OF DEFENCE ESTIMATES/ ON DEPUTATION/OUT ON DEPUTATION FROM DEFENCE C)",
    headerNote: "",
    description: "For serving Civil Defence employees covered under Defence Estimates / deputation provisions.",
    guidance: [
      "For currently serving Defence Civilian employees paid out of Defence Estimates or on deputation.",
      "Specify Current Cadre/Organisation, Current Department, and deputation details if applicable.",
      "Enter Pay Account Number as per salary slip and current designation.",
      "Requires verification & countersignature from office head and authentication by URC.",
    ],
  },
  {
    id: "esmPensionerWidowNok",
    prefix: "OE",
    title: "FOR ESM & PENSIONER WIDOW/NOK",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR ESM & PENSIONER WIDOW/NOK)",
    headerNote: "",
    description: "For ESM and eligible pensioner Widow/NOK applicants.",
    guidance: [
      "For Ex-Servicemen, Widows, Next of Kin, Emergency Commissioned, WW Veterans, and SSC pensioners.",
      "Supports Army, Navy, Airforce, and Uniformed Forces Pensioners (AR, CG, SFF, TA, GREF, BRO).",
      "Keep Pension Payment Order (PPO) Number and date of retirement ready.",
      "Up to two dependent cards can be applied for eligible dependents.",
      "Renewable annually at your nearest canteen by presenting PPO/discharge documents.",
    ],
  },
  {
    id: "servingArmedForces",
    prefix: "OA",
    title: "FOR SERVING ARMED FORCES PERSONNEL",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR SERVING ARMED FORCES PERSONNEL)",
    headerNote: "",
    description: "For currently serving Armed Forces personnel.",
    guidance: [
      "For currently serving personnel of Army, Navy, Airforce, and Uniformed Forces (AR, CG, SFF, TA, BRO).",
      "Enter current Rank, Personal Number, and Old Personal Number if recently promoted.",
      "Apply for Liquor, Grocery, and up to two Dependent cards.",
      "Enter Date of Retirement in current rank.",
      "Physical submission requires countersignature from OIC Canteen / Field Officer.",
    ],
  },
];

export const MOD_DEPARTMENTS = [
  "AFHQ",
  "NCC",
  "BRO",
  "E-in-C's Branch",
  "Ord. Factory",
  "CVD",
  "DRDO",
  "DGQA",
  "Defence Labs",
  "DPDOS",
  "Sainik School/RIMC",
  "ARC",
  "Others",
];

export const UNIFORMED_SERVICES_ESM = ["AR", "CG", "SFF", "TA", "GREF", "BRO"];
export const UNIFORMED_SERVICES_SERVING = ["AR", "CG", "SFF", "TA", "BRO"];

export const FORM_CONFIGS = {
  // --------------------------------------------------------------------------
  // 1. SERVING CADETS / RECRUITS
  // --------------------------------------------------------------------------
  cadetRecruit: {
    prefix: "OS",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR SERVING CADETS/RECRUITS IN ALL THREE SERVICES)",
    headerNote: "Note: Applicable for person holding Canteen Smart Cards of previous service (Like ACC/SCO).",
    hasApplicationType: true,
    hasAddressStep: false,
    hasDependentsStep: false,
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your single Passport Size Photo",
        line2: "Offrs-Lounge Suit/Shirt & Tie",
        line3: "Others-Civil Dress",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce"],
    ranks: ["Officer Cadet", "Recruit"],
    rankInputType: "select",
    hasCardsApplied: false,
    cardOptions: [],
    hasPayLevel: false,
    hasCategoryOfPersonnel: false,
    hasApplicantCategory: false,
    reapplyingOldCardLabel: "In case of Reapplying enter Old Cadet/Rect. Card ID",
    reapplyingOldCardField: "oldCadetCardId",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      likelyCommissioningDate: "Likely Date of Commissioning/Attestation",
    },
    hasNokName: true,
    hasSpouseNokName: false,
    receiptLines: {
      showRank: true,
      showPersonalNo: true,
      showName: true,
      showCardsAppliedFrom: false,
      showForText: true,
      showPayAccountNo: false,
      showDesignation: false,
      showDepartment: false,
    },
    declaration: [
      "All the information provided in this application form is correct to the best of my knowledge.",
      "I am liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "Certified that I am not holding any other canteen smart cards issued for any other category or any other department.",
      "On completion of my training/commissioning, I undertake to apply for Serving Armed Forces Category Canteen Smart Cards as per my rank and surrender this cadet/recruit canteen smart card at the Centre/Unit respectively.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Certified that the recruit/cadet is a trainee at this establishment. He/she is eligible and entitled to canteen smart card during training duration. Service and personal particulars of the applicant have been verified with documented service particulars and personal details vetted as correct.",
      signLabel: "*Signature & Stamp of OIC Canteen, Field Officer (Major/Equivalent)",
      roundStampLabel: "Round Stamp of Canteen",
    },
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "This card is valid for duration of training and at all canteens. After training, Rects to apply for Grocery & Liquor Card (at Training Centre) 90 days before attestation. Offr Cadets to apply for Grocery & Liquor Card from Unit. Destroy old Card once New Cards received.",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 2. AGNIVEER
  // --------------------------------------------------------------------------
  agniveer: {
    prefix: "SR",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM - AGNIVEER",
    officialSubtitle: "",
    headerNote: "",
    hasApplicationType: true,
    hasAddressStep: false,
    hasDependentsStep: false,
    photos: [
      {
        title: "ATTESTED",
        line1: "Photo to be in",
        line2: "Civil Dress",
        line3: "",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce"],
    ranks: ["AGNIVEER"],
    rankInputType: "fixed",
    hasCardsApplied: true,
    cardOptions: ["Liquor", "Grocery"],
    hasPayLevel: false,
    hasCategoryOfPersonnel: false,
    hasApplicantCategory: false,
    reapplyingOldCardLabel: "In case of Reapplying enter Old Liquor / Grocery Card ID",
    reapplyingOldCardField: "oldLiquorGroceryCardId",
    serviceDateLabels: {
      dateOfEnrolment: "Date of Enrolment",
      dateOfRelease: "Date of Release (four years from DOE)",
    },
    hasNokName: true,
    hasSpouseNokName: false,
    receiptLines: {
      showRank: true,
      showPersonalNo: true,
      showName: true,
      showCardsAppliedFrom: true,
      showForText: false,
      showPayAccountNo: false,
      showDesignation: false,
      showDepartment: false,
    },
    declaration: [
      "All the information provided in this application form is correct to the best of my knowledge.",
      "I am liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "Certified that I am not holding any other canteen smart cards issued for any other category or any other department.",
      "I am aware that the validity of my CSD Smart Cards is upto four (4) years from the Date of my Enrolment, viz ________________.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Certified that the eligibility and entitlement of the applicant for canteen services as Agniveer have been verified with documented service particulars and personal details vetted as correct.",
      signLabel: "*Signature & Stamp of Trg Offr Minimum Field Officer (Major/Equivalent)",
      roundStampLabel: "Signature & Round Stamp Canteen",
    },
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "The validity of CSD Smart Cards is four years from the Date of Enrolment.",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 3. RETIRING ARMED FORCES - CHANGE OF CATEGORY (SERVING TO ESM)
  // --------------------------------------------------------------------------
  retiringArmedForcesChangeCategory: {
    prefix: "OE",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(For Retiring Armed Forces Person Change of Category - Serving to ESM)",
    headerNote: "(To be filled 90 days before Retirement)",
    hasApplicationType: false,
    hasAddressStep: true,
    hasDependentsStep: true,
    dependentRelations: ["Son", "Daughter", "Father", "Mother", "Wife"],
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your single Passport Size Photo",
        line2: "Offrs-Lounge Suit/Shirt & Tie",
        line3: "Others-Civil Dress",
        footer: "Please Paste. Don't Staple",
      },
      {
        title: "ATTESTED",
        line1: "Paste your Photo in Civil Dress",
        line2: "without head gear with spouse",
        line3: "(no separate Photos)",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce"],
    applicantCategories: ["Superannuating", "PMR/Discharge", "SSC"],
    hasApplicantCategory: true,
    applicantCategoryLabel: "Category of Applicant",
    personnelCategories: ["Officer", "JCO", "OR"],
    hasCategoryOfPersonnel: true,
    personnelCategoryLabel: "Category",
    payLevels: ["Level 1 to 5", "Level 6 to 9", "Level 10 to 18"],
    hasPayLevel: true,
    cardOptions: ["Liquor", "Grocery", "Dependent1", "Dependent2"],
    hasCardsApplied: true,
    hasPresentlyHeldCardNo: true,
    presentlyHeldCardLabel: "Liquor/Grocery Card No. (Presently held)",
    rankLabel: "Substantive Rank on Retirement/Discharge",
    rankInputType: "text",
    reapplyingOldCardLabel: "In case of Reapplying enter Old Liquor / Grocery Card ID",
    reapplyingOldCardField: "oldLiquorGroceryCardId",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      dateOfRetirement: "Date of Retirement",
    },
    hasNokName: false,
    hasSpouseNokName: true,
    receiptLines: {
      showRank: true,
      showPersonalNo: true,
      showName: true,
      showCardsAppliedFrom: true,
      showForText: true,
      showPayAccountNo: false,
      showDesignation: false,
      showDepartment: false,
    },
    declaration: [
      "I am entitled to canteen facilities as ESM on retirement/PMR/Discharge. All the information provided in this application form is correct to the best of my knowledge.",
      "I am liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "I have applied for dependent cards only for my eligible dependents who are actually dependent on me.",
      "Certified that I am not holding any other canteen smart cards issued for any other category or any other department.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Certified that the eligibility and entitlement of the applicant as ESM on retirement/PMR/Discharge for canteen services as serving uniformed personnel have been verified with documented service particulars and personal details vetted as correct.",
      signLabel: "*Signature & Stamp of OIC Canteen / Field Officer (Major/Equivalent)",
      roundStampLabel: "Signature & Round Stamp Canteen",
    },
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "Children above 10 years authorised dependent card. (Son over 25 years not authorised. No age limit for Dependent/Widowed/Divorced Daughters).",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days. (Except Army Officers, cards are sent to MP 5 & 6).",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "All cards to be renewed Annually from 'Nearest Canteen' (without new application form). Show PPO/Discharge documents.",
      "Expiry of Card – 10 years from date of issue. Reapply three months before expiry. If primary grocery card is replaced, get active dependent cards relinked/surrendered and get entire grocery quota restored.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 4. CIVIL DEFENCE EMPLOYEES (RETIRED, RETIRING & FAMILY PENSIONERS)
  // --------------------------------------------------------------------------
  civilDefenceRetired: {
    prefix: "OC",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR CIVIL DEFENCE EMPLOYEES (RETIRED, RETIRING & FAMILY PENSIONERS))",
    headerNote: "",
    hasApplicationType: false,
    hasAddressStep: true,
    hasDependentsStep: false,
    hasStatusCheckboxes: true,
    statusOptions: ["Retired", "Retiring", "Widow", "NOK"],
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your Photo",
        line2: "with spouse",
        line3: "(no separate Photos)",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce", "MoD"],
    hasModOrgSelection: true,
    modDepts: MOD_DEPARTMENTS,
    payLevels: ["Level 1 to 5", "Level 6 to 9", "Level 10 to 18"],
    hasPayLevel: true,
    payLevelLabel: "Category of Pay Level",
    hasCardsApplied: false,
    cardOptions: [],
    hasCategoryOfPersonnel: false,
    hasApplicantCategory: false,
    isCivilDefence: true,
    hasPpoNumberAndDate: true,
    rankInputType: "designation",
    reapplyingOldCardLabel: "Old Grocery Card ID",
    reapplyingOldCardField: "oldGroceryCardId",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      dateOfRetirement: "Date of Retirement",
    },
    hasNokName: false,
    hasSpouseNokName: true,
    receiptLines: {
      showRank: false,
      showPersonalNo: false,
      showPayAccountNo: true,
      showName: true,
      showDesignation: true,
      showDepartment: true,
      showCardsAppliedFrom: true,
      showForText: false,
    },
    declarationText:
      "Certified that I am not holding any other canteen smart card issued from other category/department issued to me. All information given above is correct to the best of my knowledge. I am liable to face legal action including cancellation of Grocery Canteen Smart cards at any point of time, if the information furnished by me is found to be incorrect or the CSD facility is misused by me.",
    counterSignedText:
      "Certified that the applicant is retiring/retired from this organization is a pensioner paid out of defence estimates and all information submitted in the form is verified by me as correct as per records held with this office and to the best of my knowledge.",
    urcAuthenticationText:
      "Certified that the all personal details submitted in the application have been duly vetted with supporting documents. Salary slip/PPO is enclosed. Old Grocery Card if any will be destroyed by punching of chip before handing over newly personalised Retired Defence Civilian Grocery Smart Card.",
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "Card to be renewed Annually from 'Nearest Canteen' (without new application form). Show PPO.",
      "Expiry of Card – 10 years from date of issue. Reapply three months before expiry.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 5. SERVING CIVIL DEFENCE EMPLOYEES
  // --------------------------------------------------------------------------
  civilDefenceServing: {
    prefix: "CC",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle:
      "(FOR SERVING CIVIL DEFENCE EMPLOYEES PAID OUT OF DEFENCE ESTIMATES/ ON DEPUTATION/OUT ON DEPUTATION FROM DEFENCE C)",
    headerNote: "",
    hasApplicationType: false,
    hasAddressStep: true,
    hasDependentsStep: false,
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your single Passport",
        line2: "Size Photo in Civil Dress",
        line3: "without head Gear",
        footer: "Please Paste. Don't Staple",
      },
      {
        title: "ATTESTED",
        line1: "Paste your Photo in Civil Dress",
        line2: "without head gear with spouse",
        line3: "(no separate Photos)",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce", "MoD"],
    hasModOrgSelection: true,
    modDepts: MOD_DEPARTMENTS,
    payLevels: ["Level 1 to 5", "Level 6 to 9", "Level 10 to 18"],
    hasPayLevel: true,
    payLevelLabel: "Category of Pay Level",
    hasCardsApplied: false,
    cardOptions: [],
    hasCategoryOfPersonnel: false,
    hasApplicantCategory: false,
    isCivilDefence: true,
    hasPpoNumberAndDate: false,
    rankInputType: "designation",
    reapplyingOldCardLabel: "In case of Reapplying enter Old Grocery Card ID",
    reapplyingOldCardField: "oldGroceryCardId",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      dateOfRetirement: "Date of Retirement",
    },
    hasNokName: false,
    hasSpouseNokName: true,
    receiptLines: {
      showRank: false,
      showPersonalNo: false,
      showPayAccountNo: true,
      showName: true,
      showDesignation: true,
      showDepartment: true,
      showCardsAppliedFrom: true,
      showForText: false,
    },
    declaration: [
      "Certified that I am a Defence Civilian staff entitled to Canteen facilities under the existing rules on the subject and I will be liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "All the information provided in this application form is correct to the best of my knowledge.",
      "Certified that I am not holding any other canteen smart cards issued to me for any other category or any other department.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Verified that the applicant is borne on strength of this organisation and the eligibility and entitlement of the applicant for canteen services as Defence Civilian have been verified with Pay Slip issued by MoD/Defence establishment documents and his/her personal details are vetted as correct.",
      signLabel: "Date & Stamp of Countersigning Authority (Not below Director)",
      roundStampLabel: "Office Round Stamp of Canteen",
    },
    urcAuthenticationText:
      "Verified that the eligibility and entitlement of the applicant for canteen services as Serving Defence Civilian has been verified with enclosed Pay Slip/ Undertaking by appropriate authority, and his/her personal details vetted as correct.",
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "Card to be renewed Annually from 'Nearest Canteen' (without new application form). Show Serving Certificate.",
      "Expiry of Card – 10 years from date of issue/Date of Retirement/Date of termination of deputation, whichever is earlier. Reapply three months before expiry.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 6. ESM & PENSIONER WIDOW / NOK
  // --------------------------------------------------------------------------
  esmPensionerWidowNok: {
    prefix: "OE",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR ESM & PENSIONER WIDOW/NOK)",
    headerNote: "",
    hasApplicationType: true,
    hasAddressStep: true,
    hasDependentsStep: true,
    dependentRelations: ["Spouse", "Daughter", "Son", "Mother", "Father"],
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your single Passport",
        line2: "Size Photo",
        line3: "Offrs-Lounge Suit/Shirt & Tie, Others-Civil Dress",
        footer: "Please Paste. Don't Staple",
      },
      {
        title: "ATTESTED",
        line1: "Paste your Photo in Civil Dress",
        line2: "without head gear with spouse",
        line3: "(no separate Photos)",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce", "Others (Uniformed Forces Pensioners Only)"],
    otherServiceOptions: UNIFORMED_SERVICES_ESM,
    applicantCategories: ["ESM", "Widow", "NOK", "EC", "WW Veteran", "SSC"],
    hasApplicantCategory: true,
    applicantCategoryLabel: "Category of Applicant",
    personnelCategories: ["Officer", "JCO", "OR"],
    hasCategoryOfPersonnel: true,
    personnelCategoryLabel: "Category",
    payLevels: ["Level 1 to 5", "Level 6 to 9", "Level 10 to 18"],
    hasPayLevel: true,
    payLevelLabel: "Pay Level",
    cardOptions: ["Liquor", "Grocery", "Dependent1", "Dependent2"],
    hasCardsApplied: true,
    rankLabel: "Substantive Rank on Retirement/Discharge",
    rankInputType: "text",
    reapplyingOldCardLabel: "In case of Reapplying enter Old Liquor / Grocery Card ID",
    reapplyingOldCardField: "oldLiquorGroceryCardId",
    hasPpoNumber: true,
    ppoLabel: "Pension Pay Account No (PPO No.) If alloted",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      dateOfRetirement: "Date of Retirement",
    },
    hasNokName: false,
    hasSpouseNokName: true,
    receiptLines: {
      showRank: true,
      showPersonalNo: true,
      showName: true,
      showCardsAppliedFrom: true,
      showForText: true,
      showPayAccountNo: false,
      showDesignation: false,
      showDepartment: false,
    },
    declaration: [
      "I am entitled to canteen facilities as ESM/Widow/NOK Post retirement/PMR/discharge. All the information provided in this application form is correct to the best of my knowledge.",
      "I am liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "I have applied for dependent cards only for my eligible dependents who are actually dependent on me.",
      "Certified that I am not holding any other canteen smart cards issued for any other category or any other department.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Certified that the eligibility and entitlement of the applicant for canteen services as ESM/Pensioner/Widow/NOK have been verified with PPO/Discharge documents and personal details vetted as correct.",
      signLabel: "*Signature & Stamp of OIC Canteen/ Field Officer (Major/Equivalent)",
      roundStampLabel: "Signature & Round Stamp Canteen",
    },
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "Children above 10 years authorised dependent card. (Son over 25 years not authorised. No age limit for Dependent/Widowed/Divorced Daughters).",
      "Payment per card Rs 165/- to SCPL & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. SCPL sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from SCPL, 1st to inform application received at SCPL Noida, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "All cards to be renewed Annually from 'Nearest Canteen' (without new application form). Show PPO/Discharge documents.",
      "Expiry of Card – 10 years from date of issue. Reapply three months before expiry. If primary grocery card is replaced, get active dependent cards relinked/surrendered and get entire grocery quota restored.",
      "In case of denial of canteen facilities or any harassment please write to DDG CS, Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },

  // --------------------------------------------------------------------------
  // 7. SERVING ARMED FORCES PERSONNEL
  // --------------------------------------------------------------------------
  servingArmedForces: {
    prefix: "OA",
    officialTitle: "CANTEEN SMART CARD APPLICATION FORM",
    officialSubtitle: "(FOR SERVING ARMED FORCES PERSONNEL)",
    headerNote: "",
    hasApplicationType: true,
    hasAddressStep: false, // In PDF Page 14, page starts directly with Dependent Details!
    hasDependentsStep: true,
    dependentRelations: ["Spouse", "Daughter", "Son", "Mother", "Father"],
    photos: [
      {
        title: "ATTESTED",
        line1: "Paste your single Passport",
        line2: "Size Photo",
        line3: "Offrs-Lounge Suit/Shirt & Tie, Others-Civil Dress",
        footer: "Please Paste. Don't Staple",
      },
      {
        title: "ATTESTED",
        line1: "Paste your Photo",
        line2: "with spouse",
        line3: "(no separate Photos)",
        footer: "Please Paste. Don't Staple",
      },
    ],
    services: ["Army", "Navy", "Airforce", "Others (Uniformed Forces Pers Only)"],
    otherServiceOptions: UNIFORMED_SERVICES_SERVING,
    personnelCategories: ["Officer", "JCO", "OR"],
    hasCategoryOfPersonnel: true,
    personnelCategoryLabel: "Service Category of Personnel",
    hasApplicantCategory: false,
    payLevels: ["Level 1 to 5", "Level 6 to 9", "Level 10 to 18"],
    hasPayLevel: true,
    payLevelLabel: "Pay Level",
    cardOptions: ["Liquor", "Grocery", "Dependent1", "Dependent2"],
    hasCardsApplied: true,
    rankLabel: "Rank",
    rankInputType: "text",
    hasOldPersonalNumber: true,
    oldPersonalNumberLabel: "Old Personal No. (In case of Rank Promotion)",
    reapplyingOldCardLabel: "In case of Reapplying enter Old Liquor / Grocery Card ID",
    reapplyingOldCardField: "oldLiquorGroceryCardId",
    serviceDateLabels: {
      dateOfJoining: "Date of Joining",
      dateOfRetirement: "Date of Retirement (In Current Rank)",
    },
    hasNokName: false,
    hasSpouseNokName: true,
    receiptLines: {
      showRank: true,
      showPersonalNo: true,
      showName: true,
      showCardsAppliedFrom: true,
      showForText: true,
      showPayAccountNo: false,
      showDesignation: false,
      showDepartment: false,
    },
    declaration: [
      "All the information provided in this application form is correct to the best of my knowledge.",
      "I am liable to face disciplinary or legal action including cancellation of canteen smart cards and denial of canteen services at any point of time if the information furnished by me is found to be incorrect or false or there is any instance of misuse of CSD facility by me.",
      "I have applied for dependent cards only for my eligible dependents who are actually dependent on me.",
      "Certified that I am not holding any other canteen smart cards issued for any other category or any other department.",
    ],
    countersigned: {
      title: "VERIFIED & COUNTERSIGNED",
      text: "Certified that the eligibility and entitlement of the applicant for canteen services as serving uniformed personnel have been verified with documented service particulars and personal details vetted as correct.",
      signLabel: "*Signature & Stamp of OIC Canteen/ Field Officer (Major/Equivalent)",
      roundStampLabel: "Signature & Round Stamp Canteen",
    },
    instructions: [
      "Fill with black ball pen only. Affix only high resolution photo. Not computer generated/Photocopied. Duly attested.",
      "Children above 10 years authorised dependent card. (Son over 25 years not authorised. No age limit for Dependent/ Widowed/Divorced Daughters).",
      "Payment per card Rs 165/- to PS Quick IT Pvt Ltd & Rs 5/- to canteen. Do not pay twice if reapplying due to rejection. PS Quick IT Pvt Ltd, sends rejection note to canteen which serves as Credit Note.",
      "Expect 2 SMS from PS Quick IT Pvt Ltd, 1st to inform application received at PS Quick IT Pvt Ltd, 2nd to inform card prepared and will reach canteen in 15 working days.",
      "If you receive No SMS/Update, contact canteen or write a mail to customercare@cims-net.com giving payment and personal details.",
      "Newly prepared cards to be activated and Personal Pin generated in front of the customer. Confirm card not activated/ utilised earlier.",
      "To deny misuse & cyber frauds – do not give your canteen card to any other person, do not make photocopy/ take photo of card. Physically destroy old/expired cards. Report loss of card by lodging FIR and report to nearest canteen.",
      "Expiry of Card – 10 years from date of issue/ Date of Retirement, whichever is earlier. Reapply three months before expiry. If primary grocery card is replaced, get active dependent cards relinked/ surrendered and get entire grocery quota restored.",
      "In case of denial of canteen facilities or any harassment please write to Canteen Services Directorate, QMG Branch, West Block III, Second Floor, R. K. Puram, New Delhi, PIN-110066.",
    ],
  },
};
